[unstable]
build-std = ["alloc", "core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64_target.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
